### ISSUE TITLE
Please add Google Spatial Media Metadata Specification support

### ISSUE THREAD

**Issue by liyuxi** [Matroska-Org/matroska-specification#101]
let Matroska support VR/360-degree Video

**Comment by dericed** [comment]
Any related spec to point to for what Elements are needed?

**Comment by dericed** [comment]
Much of what is defined in https://github.com/google/spatial-media/blob/master/docs/spherical-video-v2-rfc.md#webm-matroska is already integrated in https://github.com/Matroska-Org/matroska-specification/pull/53. Can you clarify?

**Comment by robUx4** [comment]
Closing as all elements are defined in `ebml_matroska.xml`.
