### ISSUE TITLE
use unique section names

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/matroska-specification#113]
Currently a few section names are repeated in different context which breaks the TOC in the IETF html output, such as:

- Matroska Element Ordering Guidelines / Chapters
- Chapters

The section should be renamed to be unique regardless of context.

**Comment by ablwr** [comment]
Has this been resolved? I'm not able to replicate this issue and the link seems to be based on a tag styled like `rfc.section.X.X.XX`and not based on non-unique title identifiers.

**Comment by dericed** [comment]
Here are the repeated section names that I see:

- Introduction (there are 4 sections called this)
- Matroska Schema (2, one is a subsection of the other)
- Laced Data (2)
- CodecPrivate (2)
- CodecID & CodecPrivate: codec identification (2)

While looking at this, I also noticed that there are two "Chapters" subsections called:
`#Chapters`
`## Chapters`
