### ISSUE TITLE
range for LuminanceMax and LuminanceMin should be updated to hex floating point constants

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/matroska-specification#122]
see range attributes in https://github.com/Matroska-Org/matroska-specification/blob/fce29626d0c7d7d7b0a0543f82cb3da924bce8d4/ebml_matroska.xml#L548-L553

**Comment by robUx4** [comment]
This is fun

**Comment by robUx4** [comment]
Also, do we actually need ranges ? Just positive would be enough ? It also doesn't cover the minimum precision (0.1 cd/m² or 0.001 cd/m²) ?

**Comment by retokromer** [comment]
Hmm… _intuitively_, I would say that for luminance positive is enough, but the precision should be added.

**Comment by robUx4** [comment]
IMO just saying they must be positive is enough. You don't know what precision people will want to store. Namely for scientific recordings they would record the sun or very few photons in dark environments. We should be able to handle that and not reject such files. Negative luminance doesn't make much sense though.

**Comment by retokromer** [comment]
Yep, agreed: let’s go for positive only.

**Comment by dericed** [comment]
ping to @FrankGalligan

**Comment by retokromer** [comment]
FYI: I asked two of my former students working on scientific imaging (at CERN and EPFL). Both support positive only and both suggest to give the possibility (not mandatory) to store also the precision.

**Comment by robUx4** [comment]
The problem with the precision is that it's really dependent on the float format and the actual value. I don't think current video standards define the precision, just the range. The lower bound can be seen as a precision but it's not.

**Comment by retokromer** [comment]
I understand plenty your argument, but in the scientific world a value without a precision is not one. That said, I am personally fine with positive only.

**Comment by robUx4** [comment]
I think for scientific purpose the precision of the instrument would be stored separately. The precision may also vary depending on the value (low range, mid range, high range).

**Comment by retokromer** [comment]
The idea is to store as much as possible with the file itself. That’s also my dream e.g. for the LUTs and the sensor’s metadata that determine the «raw» data – this defines the way the data are cooked.

**Comment by robUx4** [comment]
Fixed after the merged changes.
