### ISSUE TITLE
How many Default Editions are allowed?

### ISSUE THREAD

**Issue by hubblec4** [Matroska-Org/matroska-specification#141]
For the moment there is no limitation, every edition entry could have the EditionFlagDefault set to true.

My opinion is we should have one default edition only.

**Comment by dericed** [comment]
Alternatively we could recommend only one edition as default but state how a player should react (for instance, we could say that the player MUST consider the first default edition as default and ignore subsequent default flags). Also is it possible that default edition handling varies depending on if the segment is linked? For instance the edition to default to in the second segment might be set by the first segment despite what the second segment's edition flags say.

**Comment by hubblec4** [comment]
If more then one edition is set to default, of course, the first Default edition MUST be used.

"> Also is it possible that default edition handling varies depending on if the segment is linked?<"
Interesting question!
Hard-Linking: 
2 or more segments with multiple editions and in the first segment the 2. edition's DefaultFlag is set to true -> 
Should a Splitter uses the 2. edition for all other hard linked segments? (If only one or no edition is present , then a Splitter use these edition or entire segment)

Medium-Linking:
I don't know how it should work there.

Soft-Linking:
The "start" segment(mkv) is important for the Default edition. All Chapter-Segment-Linkings independent from the EditionFlagDefault of the other segments(mkv's)

**Comment by hubblec4** [comment]
I worked a bit today on this topic in my new Matroska Chapters specs[https://github.com/hubblec4/Matroska-Chapters-Specs](url)

**Comment by robUx4** [comment]
If the intention is to be merged in the IETF document (replacing the old stuff), can you make a Pull Request ?

Thanks

**Comment by hubblec4** [comment]
The Pull Request is done. It is my first time, is all OK with the Request?

**Comment by ablwr** [comment]
@hubblec4 you did it correctly. :)

**Comment by hubblec4** [comment]
Can we close this issue or is more discussion required.
