### ISSUE TITLE
define Matroska Player and Matroska Reader

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/matroska-specification#194]
Not sure if we have an IETF style notations section yet, but both `Matroska Player` and `Matroska Reader` should be defined. Related comment: https://github.com/Matroska-Org/matroska-specification/pull/190#discussion_r139317047

**Comment by ablwr** [comment]
Thanks, I'll take a look at this based on the convo, etc., and propose changes / sync across documentation

**Comment by ablwr** [comment]
This seems to have been resolved. Re-open if I am mistaken.
