### ISSUE TITLE
Rename Timecode* elements to Timestamp*

### ISSUE THREAD

**Issue by robUx4** [Matroska-Org/matroska-specification#197]
Matroska doesn't actually timecodes yet. What it uses is timestamps.

The wording in paragraphs should also be updated to reflect this change.

**Comment by dericed** [comment]
IMHO this is a difficult move, particularly since several Elements contain string `Timecode`.

**Comment by robUx4** [comment]
I'll give it a try. Hopefully it's no more than search & replace.

**Comment by hubblec4** [comment]
Is all ok with the renaming?

**Comment by dericed** [comment]
looks like mkvtoolnix already made the leap: https://github.com/mbunkus/mkvtoolnix/commit/e3abad51614117031691eff26f96fce91bb4243b

**Comment by robUx4** [comment]
Fixed with #199
