### ISSUE TITLE
Cruft/ideas in Menu section

### ISSUE THREAD

**Issue by ablwr** [Matroska-Org/matroska-specification#201]
The Menu sections gets a little ill-formed at the bottom, see excerpt:

```

## Ideas

!!!! KNOW Where the main/audio/subs menu starts wherever we are (use chapters) !!!!

!!!! Keep in mind the state of the selected tracks of each kind (more than 1 for each possible) !!!!
!!!! Order of blending !!!!
!!!! What if a command is not supported by the player ? !!!!
!!!! Track selection issue, only applies when 'quitting' the menu (but still possible to change live too) !!!!
!!!! Allow to hide (not render) some parts of a movie for certain editions !!!!
!!!! Get the parental level of the player (can be changed live) !!!!


## Data Structure

As a Matroska side project, the obvious choice for storing binary data is EBML.
```

I suggest removal but seek approval.

**Comment by ablwr** [comment]
Oh I didn't mean to assign @robUx4 to solve, I was in pull-request-review mode.

**Comment by robUx4** [comment]
` ablwr assigned robUx4 and unassigned robUx4 an hour ago` too bad we can't emoji on that.

This can definitely go away.

**Comment by hubblec4** [comment]
This Menu Ideas are indeed not well-formed for the specs and maybe we should remove them.
But maybe we could keep them in an extra .md file.

I will work in the future at the Menu section and this Ideas helps me to find a way in this huge topic.

**Comment by hubblec4** [comment]
I think it is ok to have this menu.md, cause the Matroska DVD menu is more or less present and we should/must describe it.

And the Matroska Native Menu sytem is also present AND it works in practice with the VLC-player,
so here I think we must describe it.

I can add then my work in the menu.md.

**Comment by hubblec4** [comment]
In the chapters.md, the Menu feature section can be moved to this menu.md maybe.

**Comment by robUx4** [comment]
All the ideas can be turned into issues on GitHub. And they're still on matroska.org for the time being.

**Comment by hubblec4** [comment]
Ok, thats a way we can do.
But not delete the menu.md file?

**Comment by robUx4** [comment]
IMO menus (aka chapter codecs) should be part of different document. It's also different than a codec mapping as we actually define the codec.

**Comment by robUx4** [comment]
Also http://menu.md/ sounds good.

**Comment by ablwr** [comment]
OK I will clean up menu.md first as-is (after the aforementioned #200 and #198)

**Comment by dericed** [comment]
I'm curious what the semantics of a `!!!!` quoted statement is.

**Comment by robUx4** [comment]
⚠️ ⚠️ ⚠️ ⚠️
