### ISSUE TITLE
Missing elements in spec

### ISSUE THREAD

**Issue by ablwr** [Matroska-Org/matroska-specification#22]
A chunk of the spec seems to be missing -- from `MatrixCoefficients` to `LuminanceMin`. Is this intentional? Should I add them into the page?

**Comment by mbunkus** [comment]
The `Colour` element and all of its children are the ones that have been added to the specs recently. See https://github.com/Matroska-Org/foundation-source/pull/15

So yes, adding them here would be the right thing to do.

**Comment by ablwr** [comment]
Great, thanks. Please assign this task to me.

**Comment by mbunkus** [comment]
I haven't done a lot with permissions and stuff on Github yet. Looks like I can only assign tasks to collaborators of a repository. I've just added (invited?) you. Once you accept I'll assign it to you.

**Comment by ablwr** [comment]
Thank you!

**Comment by ablwr** [comment]
Due to the way we are now rendering the schema in its XML, this is no longer needed. Closing this issue.
