### ISSUE TITLE
tagging.md states ALBUM target type is level 40, should be 50

### ISSUE THREAD

**Issue by sjohannes** [Matroska-Org/matroska-specification#23]
In `tagging.md`, under [Target types](https://github.com/Matroska-Org/matroska-specification/blob/gh-pages/tagging.md#target-types), there is this sentence (after the table):

> That means if a CD has the same artist for all tracks, you just need to set the ARTIST tag at level 40 (ALBUM) and not to each TRACK (but you can).

However, the table shows that ALBUM should be level 50 instead.

**Comment by mbunkus** [comment]
Thanks, fixed. It had been wrong on the [original page](https://www.matroska.org/technical/specs/tagging/index.html) where I've fixed it as well.
