### ISSUE TITLE
Add the WebM encryption elements

### ISSUE THREAD

**Issue by robUx4** [Matroska-Org/matroska-specification#258]
WebM uses 2 elements that we don't have:

- ContentEncAESSettings
- AESSettingsCipherMode

For compatibility and convenience, we should add then to Matroska as well.

See https://www.webmproject.org/docs/webm-encryption/

**Comment by JeromeMartinez** [comment]
Interesting, do you have some corresponding sample files?

**Comment by robUx4** [comment]
Not at the moment, no.
