### ISSUE TITLE
codec_specs.md line 17 contains 404 link

### ISSUE THREAD

**Issue by bastik-tor** [Matroska-Org/matroska-specification#36]
In line 17 of codec_specs.md you link to http://www.corecodec.com/modules.php?op=modload&amp;name=PNphpBB2&amp;file=viewtopic&amp;t=227 which returns a 404.

I don't know how if there is still a resource that could be included instead or if the section would have to be reworked.

**Comment by dericed** [comment]
I tried to find the page in the wayback machine, but unfortunately corecodec.com has a rather restrictive robots.txt that prevented archive.org from crawling it.

**Comment by mbunkus** [comment]
Thanks for spotting it. I think I'm going to delete that sentence. It's not really needed for specs, and we don't have such a list anymore since the demise of corecodec.com anyway.

Additionally the mailing list address in the following sentence is wrong, too; I'll fix that
