### ISSUE TITLE
Line 178 in notes.md contains link with a 404

### ISSUE THREAD

**Issue by bastik-tor** [Matroska-Org/matroska-specification#41]
> If you want some sample code for all these calculations you can have a look at this [small C program](https://matroska.org/matroska-tcscale.c). 

Maybe the tool you created is located elsewhere these days.

**Comment by robUx4** [comment]
I do not remember this program at all. Maybe we should just remove that paragraph. It won't go into the RFC anyway.

**Comment by mbunkus** [comment]
I cannot remember either, and I cannot find such a program in the whole Matroska web site directory. Nor on my own development system. Therefore I concur; let's remove the paragraph.

**Comment by robUx4** [comment]
Fixed
