### ISSUE TITLE
cleanup table in codec specs

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/matroska-specification#46]
The nest table in https://matroska.org/technical/specs/codecid/index.html is broken in the RFC output. The nested form, for instance under V_MPEG4/ISO/??? and V_REAL/????, is challenging to replicate in the simpler formatting of the RFC.
Can these tables be restructured without nesting?

Also the structure of the table in codec spec implies that only four pieces of information are needed to define a codec for use in Matroska:
- Codec ID
- Name
- Description
- Track Type (currently Video, Audio, Subtitle, and ... Button)

Is any more data needed to define an encoding for use in Matroska?

Also the TrackType Element also supports `complex`, `logo`, and `control` track types although none appear to be defined in the codec specs page.

**Comment by dericed** [comment]
Although I pointed out the corresponding page on matroska.org, I should point out that I'm talking about https://github.com/Matroska-Org/matroska-specification/blob/gh-pages/codec_specs.md in the context of the repo.

**Comment by ablwr** [comment]
This seems to no longer be an issue. Re-open if my assumption is false.

**Comment by dericed** [comment]
+1
