### ISSUE TITLE
fixing tables in markdown

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/matroska-specification#47]
There is a section on EncryptedBlock Structure in https://github.com/Matroska-Org/matroska-specification/blob/gh-pages/index.md#encryptedblock-structure, but in the [matroska.org](https://www.matroska.org/technical/specs/index.html#encryptedblock_structure) source it is greyed out. Should this section be removed?

**Comment by ablwr** [comment]
I believe this was resolved in https://github.com/Matroska-Org/matroska-specification/commit/bfe883b9ec072c79259ecdb14ec48c3a4916556e, closing
