### ISSUE TITLE
fix issues in migration of overhead section

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/matroska-specification#48]
matroska.org included an article about [overhead](https://www.matroska.org/technical/overhead/index.html) as part of the spec, which in the repo is represented in markdown at [this page](https://github.com/Matroska-Org/matroska-specification/blob/gh-pages/overhead.md). Many of the tables in the markdown version are missing data (only the first column is migrated).

Relatedly, should this article be considered part of the format specification?

**Comment by robUx4** [comment]
No it should not.

**Comment by mbunkus** [comment]
Definitely not. We should rather remove it.
