### ISSUE TITLE
remove material redundant to EBML spec

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/matroska-specification#50]
A few sections in Matroska's draft specification seem fully redundant to the EBML specification. EBML should be a normative reference of Matroska and the redundancy should be reviewed and likely reduced.

Particularly these sections:
https://github.com/Matroska-Org/matroska-specification/blob/gh-pages/notes.md#ebml-class
https://github.com/Matroska-Org/matroska-specification/blob/gh-pages/matroska_schema_section_header.md#ebml-schema-element-attributes

**Comment by ablwr** [comment]
Information in the linked EBML Class isn't explicitly stated in the EBML spec, but it is inferred in the descriptions of Class and Element ID. I'm not sure it merits being carried over, but if it does it should be refined a bit.
