### ISSUE TITLE
Matroska's EBML Schema should be `size` attributes

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/matroska-specification#55]
Currently https://github.com/Matroska-Org/matroska-specification/blob/gh-pages/ebml_matroska.xml uses an attribute called `bytesize` but per the [ebml spec](https://github.com/Matroska-Org/ebml-specification/blob/master/specification.markdown#size) it should be called `size`.

**Comment by robUx4** [comment]
PR merged
