### ISSUE TITLE
remove/upgrade recursive attribute in the Matroska's schema

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/matroska-specification#56]
The deprecated recursive attribute still exists in a few elements.

**Comment by robUx4** [comment]
The `recursive` element is still part of the EBML Schema. It's easier to parse in XML/XSLT that the path.

**Comment by robUx4** [comment]
This seems like an EBML issue.

**Comment by ablwr** [comment]
🤔

**Comment by dericed** [comment]
The recursive element is a bit redundant but I don't mind it being there. The same issue exists for both minOccurs and maxOccurs. I'm mildly in favor of closing the issue and letting the redundancy say for readability of the schema.
