### ISSUE TITLE
rename gh-pages branch to master

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/matroska-specification#59]
Recently GitHub allows naming the master branch for Github Pages. I think renaming `gh-pages` to `master` and setting GitHub Pages to read from `master` would simplify the repo. See https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages.

**Comment by ablwr** [comment]
Agreed. I don't know if we plan to get to Pull Request 0 any time soon but that would simplify the move.

To clarify this, action items are: 
1. Get latest gh-pages and push to master branch (can be a PR but easier if done by admin).
2. Update to read from master (must be done by admin)
3. Change open PRs to be merged into master instead of gh-pages

Unless you can "rename" a branch? Is that possible?

**Comment by mbunkus** [comment]
Done. Problem is that all open pull requests against `gh-pages` have been closed automatically upon deleting the `gh-pages` branch. They'll have to be re-file. The affected pull requests are:

* [rewrite Position References as Segment Position](https://github.com/Matroska-Org/matroska-specification/pull/26)
* [360 vr elements](https://github.com/Matroska-Org/matroska-specification/pull/53)
* [maxOccurs is an integer, unbounded is an invalid value](https://github.com/Matroska-Org/matroska-specification/pull/64)
* [set unknownsizeallowed](https://github.com/Matroska-Org/matroska-specification/pull/65)
* [Cues should include the last Cluster for easier seeking to the end](https://github.com/Matroska-Org/matroska-specification/pull/69)
* [Expanding on attachments](https://github.com/Matroska-Org/matroska-specification/pull/73)
* [initial draft of cues documentation](https://github.com/Matroska-Org/matroska-specification/pull/74)

**Comment by mbunkus** [comment]
I wasn't aware those pull requests would be closed automatically, though in hindsight it makes sense. I'm sorry for the inconvenience this has caused.

**Comment by dericed** [comment]
I switched all the PR's from gh-pages to master and reopened them. I didn't expect it either but makes sense.

**Comment by mbunkus** [comment]
Thanks! So the actual order should have been:

* pull Github's `gh-pages` to local repo
* push local `gh-pages` to Github as `master`
* tell all PR submitters to update the branch
* delete `gh-pages` on Github

Again sorry for the noise.
