### ISSUE TITLE
use unknownsizeallowed attribute

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/matroska-specification#60]
We have the `unknownsizeallowed` attribute [defined](https://github.com/Matroska-Org/ebml-specification/blob/master/specification.markdown#unknownsizeallowed), we should use it. What Matroska elements are `unknownsizeallowed`?

**Comment by robUx4** [comment]
`Segment` and `Cluster` and I think that's it

**Comment by robUx4** [comment]
Maybe `Cues` as well but that's debatable. If you start writing a Cue and keep updating it while writing, there's a chance you can write the size when you're done. If you can't (like the program aborted) the Cues with no end may contain junk at the end. So it's better to force `Cues` to have a known size.

**Comment by robUx4** [comment]
Closing as `Segment` and `Cues` are currently set to `unknownsizeallowed`
