### ISSUE TITLE
chapter flag logic issue

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/matroska-specification#98]
The logic of the Chapter Flag section was very confusing. For instance it claimed that:
> There are two important flags that apply to chapter atoms: enabled and hidden. The effect of those flags always applies to child atoms of an atom affected by that flag.

But then it describes Hidden flag as affecting the Child ChapterAtom only if the parent ChapterAtom has the flag set to `true`. IIUC, the Hidden Flag "always applies to child atoms" ONLY if true, otherwise the ChapterAtom's own flags are used.

**Comment by ablwr** [comment]
Some work on Chapters done in this PR https://github.com/Matroska-Org/matroska-specification/pull/149

**Comment by dericed** [comment]
I think with @hubblec4's work, this might be ready to close. Any other opinion?

**Comment by hubblec4** [comment]
Can be closed!
